(test
 (name api_tests)
 (enabled_if
  (= %{context_name} "default"))
 (libraries
  test_utils
  mollymawk_libraries
  alcotest
  albatross
  yojson
  mrmime
  uuidm
  mirage-crypto-rng
  mirage-crypto-rng.unix
  ptime
  fmt
  x509
  ipaddr
  ohex
  http-mirage-client
  emile
  tyxml
  uri
  duration
  lwt.unix
  tcpip.stack-socket
  paf
  paf.mirage
  oneffs
  mirage-block
  mirage-kv
  mimic-happy-eyeballs
  sendmail-mirage
  colombe.emile
  dns-client-mirage
  happy-eyeballs-mirage
  tls-mirage
  mirage-runtime
  multipart_form
  multipart_form-lwt))

(copy_files# ../../*.ml)
